### ISSUE TITLE
MS SQL Server Create table statement parsing error

### ISSUE THREAD

**Issue by shilohooo** [TylerBrinks/SqlParser-cs#16]
`Env`
- .NET: 8.0
- SqlParserCS: 0.3.0
- IDE: JetBrains Rider 2023.3

`code`
```csharp
using SqlParser;
using SqlParser.Dialects;

const string sql = """
                   create table T_Users(
                       id bigint primary key identity ,
                       username varchar(255) not null
                   );
                   """;

var ast = new Parser().ParseSql(sql, new MsSqlDialect());
```

`result`

```csharp
Unhandled exception. SqlParser.ParserException: Expected ',' or ')' after column definition, found identity, Line: 2, Col: 27
   at SqlParser.Parser.ThrowExpected(String expected, Token actual)
   at SqlParser.Parser.ParseColumns()
   at SqlParser.Parser.ParseCreateTable(Boolean orReplace, Boolean temporary, Nullable`1 global, Boolean transient)
   at SqlParser.Parser.ParseCreate()
   at SqlParser.Parser.ParseKeywordStatement(Word word)
   at SqlParser.Parser.ParseStatement()
   at SqlParser.Parser.ParseStatements()
   at SqlParser.Parser.ParseSql(ReadOnlySpan`1 sql, Dialect dialect, ParserOptions options)
   at Program.<Main>$(String[] args) in C:\Users\shiloh\code\csharp\learn-csharp\SqlParserDemo\SqlParserDemo\Program.cs:line 12

Process finished with exit code -532,462,766.

```

Please tell me what went wrong, thanks:)

**Comment by TylerBrinks** [comment]
This appears to be a bug in the Rust implementation as well.  I've files a defect with the Rust implementation which will be picked up here as well.

**Comment by shilohooo** [comment]
Ok:)

**Comment by shilohooo** [comment]
Finally:)

They fixed the bug after 2 years 😄
