### ISSUE TITLE
ROW_FORMAT not supported when parsing MySQL create table statement.

### ISSUE THREAD

**Issue by AmritD** [TylerBrinks/SqlParser-cs#45]
Here is an example of MySQL create table statement that I am trying to parse:
```csharp
var testCreateTableStatement = """
                               CREATE TABLE `balloons` (
                                                           `id` int(11) NOT NULL AUTO_INCREMENT,
                                                           `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                                           `created_at` datetime DEFAULT NULL,
                                                           `updated_at` datetime DEFAULT NULL,
                                                           PRIMARY KEY (`id`),
                                                           KEY `index_balloons_on_name` (`name`)
                               ) ENGINE=InnoDB AUTO_INCREMENT=7805 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
                               """;

var ast = new Parser().ParseSql(testCreateTableStatement, new MySqlDialect());
```
This fails to parse and fails with the following error:
```csharp
SqlParser.ParserException: Expected end of statement, found ROW_FORMAT, Line: 56, Col: 89
   at SqlParser.Parser.ParseStatements()
   at SqlParser.Parser.ParseSql(ReadOnlySpan`1 sql, Dialect dialect, ParserOptions options)
   at Program.Main() in 
```

I tried placing ROW_FORMAT before COLLATE to see if that would fix the issue and it does not. Looks like ROW_FORMAT is not supported since only way I can get the above code to work is if I remove `ROW_FORMAT=DYNAMIC` from the create table statement.

**Comment by TylerBrinks** [comment]
I may have to cross-post this to the SqlParser-rs project.  I will try and reproduce it there; if so I tend to post issues there and pick them up here as part of ongoing development.
